[package]
name = "netservices"
description = "A set of tools for building scalable microservice-based apps and P2P nodes in a privacy-preserving way"
authors = ["Dr. Maxim Orlovsky <orlovsky@cyphernet.org>"]
keywords = ["privacy", "cypherpunk", "tor", "microservices", "reactor"]
categories = ["network-programming", "cryptography", "concurrency"]
homepage = "https://cyphernet.org"
repository = "https://github.com/Cyphernet-DAO/rust-netservices"
version = "0.1.0"
rust-version = "1.65"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
amplify = "4.0.0-beta.1"
io-reactor = { version = "0.1.0", optional = true }
ed25519-compact = "2.0.4"
cyphernet = { version = "0.1.0", features = ["ed25519", "pem", "multibase", "noise_sha2", "noise_x25519", "noise-framework", "mixnets"] }
mio = { version = "0.8.5", optional = true }
socket2 = { version = "0.4.7", optional = true }
libc = "0.2.138"
log_crate = { package = "log", version = "0.4.17", optional = true }
rand = "0.8.5" # Used in SplitIo shared secret

[dev-dependencies]
cyphernet = { version = "0.1.0", features = ["ed25519"] }
bitcoin_hashes = "0.11.0"
log_crate = { package = "log", version = "0.4.17" }

[features]
default = ["reactor", "socket2"]
all = ["reactor", "connect_nonblocking", "mio", "log"]
reactor = ["io-reactor", "connect_nonblocking"]
log = ["log_crate", "io-reactor/log"]
connect_nonblocking = ["socket2"]
